module.exports = [
  'erlenmeyer flasks',
  'fleetwood mac',
  'idaho',
  'japanese spider crabs',
  'oracles',
  'ursula',
  'vcrs',
  'acupuncture',
  'americano',
  'anything broken',
  'anything pointy',
  'anything warty',
  'anything with lots of legs',
  'aromatherapy',
  'bat houses',
  'bats',
  'beetles',
  'bogs',
  'brews',
  'buckwheat',
  'cardamom',
  'cats',
  'cauldrons',
  'chocolate bell peppers',
  'claws',
  'climbing plants',
  'cloves',
  'coconut la croix',
  'consignment',
  'crows',
  'crushed velvet',
  'crystal',
  'dead leaves',
  'dried fruit',
  'experiments',
  'farrow',
  'fava beans',
  'ferrets',
  'hard bound books',
  'incense',
  'ivy',
  'just hairy warts',
  'ladders',
  'mauve',
  'mead',
  'mismatched tiles',
  'mold',
  'needles',
  'orbs',
  'peppercorns',
  'purple kale',
  'rats',
  'ravens',
  'robes',
  'sage',
  'shark eggs',
  'spider eggs',
  'spider webs',
  'spiders',
  'squid ink pasta',
  'stranger things',
  'swamps',
  'talons',
  'tarot cards',
  'tea',
  'teeth',
  'the number 13',
  'the moon',
  'thorns',
  'thorny plants',
  'thyme',
  'trellis',
  'tumbleweeds',
  'turrets',
  'vats',
  'venus fly traps',
  'vials',
  'vultures',
  'whiskers',
  'willows',
  'wraught iron',
];
