module.exports = [
  'erlenmeyer flask',
  'fleetwood mac',
  'idaho',
  'japanese spider crab',
  'oracles',
  'ursula',
  'vcr',
  'acupuncture',
  'americano',
  'anything broken',
  'anything pointy',
  'anything warty',
  'anything with lots of legs',
  'aromatherapy',
  'bat house',
  'bat',
  'beetle',
  'bog',
  'brew',
  'buckwheat',
  'cardamom',
  'cat',
  'cauldron',
  'chocolate bell pepper',
  'claw',
  'climbing plant',
  'clove',
  'coconut la croix',
  'consignment',
  'crow',
  'crushed velvet',
  'crystal',
  'dead leaf',
  'dried fruit',
  'experiment',
  'farrow',
  'fava bean',
  'ferret',
  'hard bound book',
  'incense',
  'ivy',
  'hairy wart',
  'ladder',
  'mauve',
  'mead',
  'mismatched tile',
  'mold',
  'needle',
  'orb',
  'peppercorn',
  'purple kale',
  'rat',
  'raven',
  'robe',
  'sage',
  'shark egg',
  'spider egg',
  'spider web',
  'spider',
  'squid ink pasta',
  'stranger things',
  'swamp',
  'talon',
  'tarot card',
  'tea',
  'teeth',
  'the number 13',
  'the moon',
  'thorn',
  'thorny plant',
  'thyme',
  'trellis',
  'tumbleweed',
  'turret',
  'vat',
  'venus fly trap',
  'vial',
  'vulture',
  'whisker',
  'willow',
  'wraught iron',
];
